#GitHub
username: ardeego
repo: ardeego.github.io 
branch: source

# Jekyll source / destination
source: .
destination: _site

# Site settings
title: ardeego
header-img: img/home-bg.jpg
email: niko@ardeego.com
copyright_name: ardeego
description: "Testing"
baseurl: "/ardeego"
url: "https://ardeego.github.io"
twitter_username: ardeego
github_username:  ardeego

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
